//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Yuzu ViewModel Generator v1.0.0.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Yuzu ViewModel Builder
// 2019-10-02T12:22:49Z